### ISSUE TITLE
Unsatisfied link error on aarch64 based MacOS

### ISSUE THREAD

**Issue by jackluo923** [y-scope/clp-ffi-java#41]
### Bug

`java.lang.UnsatisfiedLinkError: 'long com.yscope.clp.irstream.AbstractClpIrOutputStream.createNativeState()'`

### clp-ffi version

latest

### Environment

MacOS on aarch64

### Reproduction steps

- Run existing unit test

**Comment by kirkrodrigues** [comment]
Fixed by #50.
